### ISSUE TITLE
Invalid strings could be handled better

### ISSUE THREAD

**Issue by bortzmeyer** [ratopi/base45#1]
The documentation says "Calling decode with an illegal input string (like <<"GGW">>, which leads to 65536), will throw an illegale_encoding exception" but it is not true for all invalid strings. For instance, <<"=">> will throw a function clause exception.

**Comment by ratopi** [comment]
Thank you for your hint. I'm currently thinking about the <<=>> "problem". What is the correct result? 0 or an error?
What do you think?

**Comment by bortzmeyer** [comment]
IMHO, same error as <<"GGW">> since I don't think it is valid Base45.

**Comment by ratopi** [comment]
IMHO it is a different error, due to the fact the "=" does not exist in the base45-alphabet.  Therefore I will introduce a second error.

**Comment by ratopi** [comment]
Fixed in version 2.0.0
