### ISSUE TITLE
Update README.md for the RFC

### ISSUE THREAD

**Issue by bortzmeyer** [ratopi/base45#2]
The `README.md`says "Implementing encoding as defined in the proposal: https://datatracker.ietf.org/doc/draft-faltstrom-base45/" but this draft has now been published as a RFC, [RFC 9285](https://www.rfc-editor.org/info/rfc9285).

**Comment by ratopi** [comment]
Thanks a lot for your info. I will change the readme soon.

**Comment by ratopi** [comment]
Changes in commit d446d145f2c4185db978ef0ac2b7891b725dc37e
